SELECT LAST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON D.DEPARTMENT_ID = E.DEPARTMENT_ID;
--COLUNAS COM O MESMO NOME TEM QUE SER IDENTIFICADAS ANTES COM O NOME DA ENTIDADE MÃE
--APELIDO DAS ENTIDADES DO LADO DE SEUS NOMES

SELECT FIRST_NAME, DEPARTMENT_NAME, STREET_ADDRESS, COUNTRY_NAME, JOB_TITLE
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON L.LOCATION_ID = D.LOCATION_ID
JOIN COUNTRIES C
ON C.COUNTRY_ID = L.COUNTRY_ID
JOIN JOBS J
ON J.JOB_ID = E.JOB_ID;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E 
LEFT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E 
RIGHT OUTER JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E 
FULL JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

